### PR TITLE
Fix invalid dates showing as valid

### LINKED ISSUE #210: [PE-D][Tester B] Mismatch between confirmation and actual deadline
A deadline can be added on the 31st of February, but it will display (correctly) in the GUI as 28th, but the confirmation at the top is 31st.

Steps to recreate:
editP 4 d/31-02-2009

Screenshot 2023-11-03 at 4.48.50 PM

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: SungMatt/ped#4

### LINKED ISSUE #220: [PE-D][Tester E] Mismatch between displayed command result and actual result in application when doing editP for a deadline.
When editing the deadline of a project, with an invalid date say 31-02-2024, the command result box shows the project was edited with new deadline of 31-02-2024 but in the project list the date shown is 29-02-2024

Perhaps the two dates could be made to match.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: timetraveller-123/ped#7

### PR DESCRIPTION
**Pull request by aslam341**
Fixes #210, #212 and #220 .

`31-02-2021` used to be a valid user input date for project deadlines, and the program automatically changes it to `28-02-2021` as February does not have 31 days. This is no longer the case, and the program is more strict in disallowing such invalid inputs.

Codecov fails due to test-coverage, but it's a non-issue.

### CODE REVIEW

File: src/test/java/seedu/address/logic/parser/DeadlineProjectCommandParserTest.java [hunk 1]
```diff
@@ -59,7 +59,7 @@ public void parse_invalidDeadline_failure() {
     @Test
     public void parse_invalidIndex_failure() {
         // Invalid index
-        String userInput = "-1" + " " + PREFIX_DEADLINE + "31-02-2023";
```
Comment (antonTan96) [inline src/test/java/seedu/address/logic/parser/DeadlineProjectCommandParserTest.java:62]: Nice catch on seperating 2 negative test cases that are merged together!

**Review by antonTan96 — APPROVED** [review]
LGTM!
